version: '3.9'

services:
  tor-service:
    container_name: tor-service
    build: .
    ports:
      - "0.0.0.0:9000:9000" # HAProxy Port
      # - "0.0.0.0:9001:9001"
    environment:
      - NUM_TOR_INSTANCES=2 # Number of Tor instances you want to run default is 5
      - HAPROXY_USERNMAE=admin # default value is admin
      - HAPROXY_PASSWORD=admin # default value is admin
