version: "3.9"

services:
  scraping-service:
    container_name: scraping-service
    build:
      context: .
      dockerfile: ./Dockerfile
      tags:
        - hatemjaber/tor-rotator:latest
        - hatemjaber/tor-rotator:1.0.0
    image: hatemjaber/tor-rotator:latest
